name: SimpleCalendarWidget
options:
  bundleIdPrefix: de.octoco
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

schemes:
  SimpleCalendarWidget:
    build:
      targets:
        SimpleCalendarWidget: all
        CalendarWidgetExtension: all
    run:
      config: Debug
      executable: SimpleCalendarWidget

targets:
  SimpleCalendarWidget:
    type: application
    platform: macOS
    sources:
      - SimpleCalendarWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.octoco.simplecalendarwidget
        PRODUCT_NAME: Simple Calendar Widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QDK2Q7622N
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: SimpleCalendarWidget/SimpleCalendarWidget.entitlements
    dependencies:
      - target: CalendarWidgetExtension

  CalendarWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - CalendarWidgetExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.octoco.simplecalendarwidget.widget
        PRODUCT_NAME: CalendarWidgetExtension
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QDK2Q7622N
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: CalendarWidgetExtension/CalendarWidgetExtension.entitlements
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: AppIntents.framework
      - sdk: SwiftUI.framework
    info:
      path: CalendarWidgetExtension/Info.plist
      properties:
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        EXAppExtensionAttributes:
          EXExtensionPointIdentifier: com.apple.widgetkit-extension
